// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'assets_test.dart' as assets_test;
import 'contenttype_test.dart' as contenttype_test;
import 'entry_test.dart' as entry_test;
import 'image_transform_test.dart' as image_transform_test;
import 'query_test.dart' as query_test;
import 'stack_test.dart' as stack_test;

void main() {
  assets_test.main();
  query_test.main();
  stack_test.main();
  contenttype_test.main();
  image_transform_test.main();
  entry_test.main();
}
