
// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'assets_test.dart' as asset;
import 'contenttype_test.dart' as content_type;
import 'entry_test.dart' as entry;
import 'image_transform_test.dart' as image_transform;
import 'query_test.dart' as query;
import 'stack_test.dart' as stack;

void main(){
  asset.main();
  content_type.main();
  entry.main();
  query.main();
  stack.main();
  image_transform.main();
}
