name: contentstack
description: Contentstack is a headless CMS with an API-first approach that puts content
  at the centre.
version: 0.1.1
homepage: https://github.com/contentstack/contentstack-dart
documentation: https://www.contentstack.com/docs/platforms/dart/api-reference/

environment:
  # sdk: '>=2.0.0 <3.0.0'
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  http: '>=0.11.3 <0.13.0'
  http_parser: ^3.0.0
  json_annotation: any
  dartdoc: ^0.36.0
  logger: ^0.9.1
  super_enum: ^0.5.0
  lint: ^1.3.0
  dotenv: ^2.0.0


dev_dependencies:
  pedantic: ^1.9.2 # The Dart analyzer settings and best practices used internally at Google.
  test: ^1.14.4
  test_coverage: ^0.4.3
  build_runner: any
  build_test: ^0.10.3
  json_serializable: any
  build_web_compilers: '>=1.2.0 <3.0.0'
  super_enum_generator:

