name: contentstack
description: Contentstack is a headless CMS with an API-first approach that puts content
  at the centre.
version: 0.1.0
homepage: https://github.com/contentstack/contentstack-dart
documentation: https://www.contentstack.com/docs/platforms/dart/api-reference/

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: '>=0.11.3 <0.13.0'
  http_parser: ^3.0.0
  json_annotation: any
  dartdoc:
  logger: ^0.9.1
  super_enum: ^0.4.2
  lint: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_coverage: ^0.4.2
  build_runner: any
  build_test: ^0.10.3
  json_serializable: any
  build_web_compilers: '>=1.2.0 <3.0.0'
  super_enum_generator:
