name: contentstack
description: Contentstack is a headless CMS with an API-first approach that puts content
  at the centre.
version: 0.1.1
homepage: https://github.com/contentstack/contentstack-dart
documentation: https://www.contentstack.com/docs/platforms/dart/api-reference/

environment:
  sdk: '>=2.0.0 <3.0.0'
  # sdk: '>=2.8.1 <3.0.0'
  

dependencies:
  # contentstack_utils: ^0.1.0
  dartdoc: any
  dotenv: ^2.0.0
  http: '>=0.11.3 <0.13.0'
  http_parser: ^3.0.0
  json_annotation: any
  lint: ^1.3.0
  logger: ^0.9.1
  path: ^1.7.0
  super_enum: ^0.5.0


dev_dependencies:
  build_runner: any
  build_test: ^0.10.3
  build_web_compilers: '>=1.2.0 <3.0.0'
  json_serializable: any
  pedantic: ^1.9.2 # The Dart analyzer settings and best practices used internally at Google.
  super_enum_generator:
  test: ^1.14.4
  test_coverage: ^0.4.3
  

