name: contentstack
description: Contentstack is a headless CMS with an API-first approach that puts content at the centre.
version: 0.3.0
homepage: https://github.com/contentstack/contentstack-dart
documentation: https://www.contentstack.com/docs/developers/dart/api-reference/contentstack/contentstack-library.html

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  dartdoc: # dartdoc to generate HTML documentation for your Dart package
  dotenv: ^2.0.0 # loads environment variables at runtime from a .env file.
  http: ^0.12.2 # Future-based API for HTTP requests
  json_annotation: any # create code for JSON serialization and deserialization.
  logger: ^0.9.1 # logger which prints beautiful logs
  path: ^1.7.0 # for manipulating paths: joining, splitting, normalizing, etc.
  super_enum: ^0.5.0


dev_dependencies:
  build_runner: any
  build_test: ^0.10.3
  build_web_compilers: ^2.8.0
  json_serializable: any
  pedantic: ^1.9.2
  test: ^1.14.4
  test_coverage: ^0.4.3
  

