name: contentstack
description: Contentstack is a headless CMS with an API-first approach that puts content at the centre.
version: 0.5.1
homepage: https://www.contentstack.com
documentation: https://www.contentstack.com/docs/developers/apis/content-delivery-api

environment:
  # sdk: ">=2.17.6 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartdoc: ^8.1.0 # dartdoc to generate HTML documentation for your Dart package
  http: ^1.2.2 # Future-based API for HTTP requests
  json_annotation: ^4.4.0 # create code for JSON serialization and deserialization.
  logger: ^2.4.0 # logger which prints beautiful logs
  path: ^1.8.0 # for manipulating paths: joining, splitting, normalizing, etc.
  # super_enum: ^0.5.0
  dotenv: ^4.2.0 # loads environment variables at runtime from a .env file.
  file: ^7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.0.4
  build_test: ^2.1.0
  build_web_compilers: ^4.0.11
  json_serializable: ^6.1.5
  test: ^1.20.1
