name: contentstack
description: Contentstack is a headless CMS with an API-first approach that puts content at the centre.
version: 0.3.0
homepage: https://github.com/contentstack/contentstack-dart
documentation: https://www.contentstack.com/docs/developers/dart/api-reference/contentstack/contentstack-library.html

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  dartdoc: any # dartdoc to generate HTML documentation for your Dart package
  dotenv: ^3.0.0 # loads environment variables at runtime from a .env file.
  http: ^0.13.3 # Future-based API for HTTP requests
  json_annotation: ^4.0.1 # create code for JSON serialization and deserialization.
  logger: ^1.0.0 # logger which prints beautiful logs
  path: ^1.8.0 # for manipulating paths: joining, splitting, normalizing, etc.
  super_enum: ^0.5.0

dev_dependencies:
  build_runner: ^2.0.4
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
  json_serializable: ^4.1.3
  pedantic: ^1.11.0
  test: any
  # test_coverage: any
