name: Dart CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Build runner
      run: pub run build_runner build
    - name: Run coverage
      run: pub run test_coverage && pub global activate remove_from_coverage && pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$' && genhtml -o coverage coverage/lcov.info
    - name: Run tests
      run: pub run test
