# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # tag pattern on pub.dev: 'v{{version}'
  release:
    types: [ created ]

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write  # Required for OIDC authentication
    name: 'Publish to pub.dev'
    environment: 'pub.dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Test Publish (Dry Run)
        run: dart pub publish --dry-run
      - name: Publish
        run: dart pub publish --force